name: dl4amproj
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pytorch::pytorch
  - pytorch::cudatoolkit=11.5
  - matplotlib
  - pandas
  - librosa
  - resampy
  - tqdm
  - tensorboard
  - pip:
    - torch_tb_profiler
